[package]
name = "tracing-examples"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing-subscriber = { version = "0.3.22" }
tracing.workspace = true
instrumentation = { path = "../instrumentation" }
